### ISSUE TITLE
Don't lint if somebody is only labelling a PR

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge-webservices#1]

**Comment by jakirkham** [comment]
Must have seen me mucking around with labels. :wink: Definitely agree.

**Comment by pelson** [comment]
As per #2 - we never get a repeated comment now, so it doesn't really matter that the service does more work than it needs to - we don't get the extra comments anyway. Maybe we will want to look at reducing the work done in the future, but for now let's call this one done. :+1:
