### ISSUE TITLE
Switching buildpack

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#10]
Would it be possible to switch to [this buildpack]( https://github.com/conda/conda-buildpack ). This seems to be the one under the conda org so it might be better to use something a bit more official. Admittedly, it hasn't seen an update in awhile. However, if we switch and PR any needed improvements, I expect it will quickly be caught up.

**Comment by pelson** [comment]
So long as it supports setting channels (https://github.com/conda-forge/conda-forge-webservices/blob/master/environment.yml#L4) I'm :+1: on this.

**Comment by jakirkham** [comment]
Right, so what @msarahan was [saying earlier]( https://gitter.im/conda-forge/conda-forge.github.io?at=5701d3d1bbffcc665fabcd35 ) is that we might be able to take over maintenance of [that buildpack]( https://github.com/conda/conda-buildpack ). I was thinking it might be nice that we actually have control of our buildpack. Also, it would be nice for this buildpack to be the official one for `conda`.

**Comment by jakirkham** [comment]
Alternatively we could just create a buildpack here in a new repo. Let's briefly discuss whether that repo can be opened up with @msarahan when we meet tomorrow.

**Comment by pelson** [comment]
This repo is now using the https://github.com/weibeld/heroku-buildpack-run buildpack to give us more flexibility in how environments are installed and created.
