### ISSUE TITLE
Different GitHub tokens for each service

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#122]
To avoid bogging down the different services gathered here, we should try to get them to use different GitHub tokens. Right now they all use the linter's token. However we can at least get team updates and feedstock updates to use the coordinator's token as was done in the webpage repo. We may need to check what other bots are used for and add them as needed. This all in an attempt to avoid going over GitHub's rate limit.

**Comment by isuruf** [comment]
+1. Note that the webservices using `conda_smithy` will have to use the same token.

**Comment by isuruf** [comment]
Maybe we should print the rate limit in heroku log after each webservice to get an idea of how big of an issue this is going to be.

**Comment by jakirkham** [comment]
That's a good idea. There's a few lines of code at staged-recipes that could be pilfered for this purpose.

**Comment by jakirkham** [comment]
As for the `conda-smithy` point, maybe we can swap out the tokens somehow while services are running. Alternatively we can investigate some override mechanism for `conda-smithy`.

**Comment by jakirkham** [comment]
Fixed feedstock updates to use a different token. Though it is shared by the webpage repo.

**Comment by beckermr** [comment]
The code now uses an app token when possible which has a rate limit that is >2x a normal token. Closing this as addressed.
