### ISSUE TITLE
recipe order is non deterministic

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge-webservices#13]
I seem to remember it uses glob, which doesn't result guarantee any particular sort order. I saw this in https://github.com/conda-forge/staged-recipes/pull/356.

**Comment by pelson** [comment]
Indeed it does: https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/linting.py#L42

**Comment by jakirkham** [comment]
Fixed by PR ( https://github.com/conda-forge/conda-forge-webservices/pull/14 ).
