### ISSUE TITLE
Handle removal of teams and feedstocks

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#132]
Would be good to be able to handle removal of teams and feedstocks.

**Comment by jakirkham** [comment]
This should be relatively straightforward for both. Should give us an opportunity to refactor a bit as well.

**Comment by jakirkham** [comment]
For the `feedstocks` repo, this amounts to calling [`remove`]( http://gitpython.readthedocs.io/en/stable/reference.html#git.objects.submodule.base.Submodule.remove ) on the submodule and committing the change (it should already be staged). Everything else works basically the way we have it now.

**Comment by beckermr** [comment]
We don't remove, only archive. Closing.
