### ISSUE TITLE
Handle renaming of teams and feedstocks

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#133]
Would be good to be able to handle renaming of teams and feedstocks.

**Comment by jakirkham** [comment]
Am less clear what our end goal should be. Are we trying to solve renaming feedstocks generally ( https://github.com/conda-forge/conda-forge.github.io/issues/179 )? If so, that might be best as a different webservice.

**Comment by beckermr** [comment]
We don't rename, only archive. Closing.
