### ISSUE TITLE
Runaway team update bot

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#151]
Looks like the bot got a little overexcited about updating the team in issue ( https://github.com/conda-forge/pandoc-feedstock/issues/21 ). Not sure what happened, but am pretty sure it is unintended.

**Comment by pkgw** [comment]
See also conda-forge/healpy-feedstock#9.

**Comment by pkgw** [comment]
Ahhhh I made it start comment again!!! No!!! Sorry @mwcraig.

**Comment by pkgw** [comment]
Based on what just happened, maybe it will make a comment whenever it sees any comment on the relevant issue, rather than just when it sees a comment requesting a team update?

**Comment by isuruf** [comment]
Thanks, I was confused why this happened, but the report on what happened today was helpful in figuring it out
