### ISSUE TITLE
Feedstock deletion webservice

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#152]
There are a number of things that need to be done when deleting a feedstock. This process is a bit onerous and there is a chance that a step gets missed. It would be ideal if a webservice handled all of these steps for us. Here's a rough listing of what needs to be done.

1. Delete the repo.
2. Delete AppVeyor project.
3. Disable Travis CI for the project and resync.
4. Unfollow the CircleCI project and remove the checkout SSH key (there is a bot doing this).
5. Deleted packages from Anaconda.
6. Delete the associated team from GitHub.
7. Remove the submodule from the feedstock listing.
8. Refresh the feedstock listing webpage.

Note: It's totally possible I'm missing a step, but from memory this is what it looks like. May refresh the list if other things are mentioned or come to mind.

**Comment by pelson** [comment]
FWIW, I'd put this in conda-smithy, and simply call it from here (the webservices code should be as lightweight as possible).

**Comment by jakirkham** [comment]
Lately it seems that people prefer archiving feedstocks to deleting them. Given this, will close this as "won't fix".
