### ISSUE TITLE
Bot to ping listed maintainers on staged-recipes

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-webservices#153]
_From @CJ-Wright on November 25, 2017 3:18_

It might be good to have a bot (like the linter) which pings the listed maintaners in staged-recipes. This would be doubly good if it was done after all the tests passed.

_Copied from original issue: conda-forge/conda-forge.github.io#495_

**Comment by jakirkham** [comment]
Given we ping people in the feedstock now, is this sufficiently resolved or is there more we should be doing?

**Comment by CJ-Wright** [comment]
I meant that for maintainers being ok for addition

**Comment by beckermr** [comment]
Done via the ping team command
