### ISSUE TITLE
Update CI keys

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge-webservices#154]
It would be nice to have a bot to update the CI keys upon request. Currently we need to put in a new PR into staged-recipes which can be annoying.

**Comment by CJ-Wright** [comment]
Attn: @isuruf

**Comment by jakirkham** [comment]
I think the expired SSH keys are based on age. Maybe it would be better to try something similar to what we did with expired tokens using a branch at `staged-recipes`. So we don’t have to deal with them one at a time.

**Comment by jakirkham** [comment]
I think this was resolved with PR ( https://github.com/conda-forge/conda-forge-webservices/pull/158 ). Could you please check @CJ-Wright?

**Comment by CJ-Wright** [comment]
I readded that feedstock so I can't test it but next time someone runs into a feedstock to readd we can tell them to test it

**Comment by jakirkham** [comment]
So we have already tested updating the CircleCI SSH checkout key in other feedstocks (e.g. https://github.com/conda-forge/conda-smithy-feedstock/issues/88 ). Mainly trying to make sure that was what this issue was about and not something else.

**Comment by CJ-Wright** [comment]
Yea, that sounds good, closing.
