### ISSUE TITLE
Autorequest reviews of maintainers on feedstocks

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#164]
It is really hard to see all PRs on feedstocks that I maintain. While there are tools like [this]( https://minrk.github.io/all-my-pulls/ ), which are great. They don't really work for core. Not to mention, such a tool may quickly become overwhelmed with conda-forge's size. Suppose there is another argument that users have to be comfortable using a tool outside the normal GitHub workflow.

Was trying to think of ways to improve this and it occurred to me that we could autorequest reviews from all maintainers when a PR comes into a feedstock. It does increase the number of notifications for a PR, but it also makes it easier to find later and the notification is quite minimal. We could consider assignment as well except IIUC it is limited to one user so it cannot include multiple.

Thoughts on this proposal? Other ways to tackle this problem?

cc @conda-forge/core

**Comment by CJ-Wright** [comment]
Would it be possible to request review only after success or failure?

**Comment by jakirkham** [comment]
Sure, that should be possible. GitHub sends out notifications for success and they have one specifically for all notifications being successful.

Guess this does point out a flaw in using review requests to track this, as they aren't really applicable to PRs that aren't review ready (i.e. failing), but may still need help. Still, on the whole, think this would be an improvement.

**Comment by CJ-Wright** [comment]
If a build fail I would still notify the maintainers (since most likely they need to fix something in the PR or provide some guidance).

**Comment by dougalsutherland** [comment]
I'd definitely appreciate it only happening after CIs are done, if feasible; I've often looked at a PR and thought "okay, I'll come back and actually look once I know the CI status," and then sometimes forgotten to actually do that.

**Comment by jakirkham** [comment]
Just sketching this out a bit, we can register for a [StatusEvent]( https://developer.github.com/v3/activity/events/types/#statusevent ), which notifies us of any status change. If the status is pending, we ignore it. If the status is anything else (i.e. success, failure, or error), we can [check the combined status]( https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref ). If the combined status is anything other than pending, we can request reviews from the maintainers.

Thoughts on this?

**Comment by beckermr** [comment]
the codeowners file does this now though it is a bit early in the process - I am going to close this for now, but we can reopen later

we could have the automerge bot do this as well

**Comment by jakirkham** [comment]
Yep thanks! 😀
