### ISSUE TITLE
Missing argument in call to `rerender()`

### ISSUE THREAD

**Issue by ericdill** [conda-forge/conda-forge-webservices#165]
Seems like we're missing a positional arg for ``pr_num`` [here in commands.py](https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/commands.py#L119).  I'm not 100% sure what this should be, exactly. It seems like rerender is expecting an active pull request when it is called but the call to rerender linked above appears to be working on local repo before the PR has been created on GH.

**Comment by isuruf** [comment]
It should be `rerender(git_repo, issue_num)`. Want to send a PR?
