### ISSUE TITLE
Upgrade to python 3.6?

### ISSUE THREAD

**Issue by ericdill** [conda-forge/conda-forge-webservices#167]
Seems like we're force installing python 3.5 in the heroku buildpack. Should we consider moving that to python 3.6?

relevant PR: https://github.com/conda-forge/conda-forge-webservices/pull/95

[buildpack line](https://github.com/conda-forge/conda-forge-webservices/blob/master/buildpack-run.sh#L25)

**Comment by jakirkham** [comment]
Yeah, we should. Though we should probably still pin it (just to 3.6 instead). This was done as some `defaults` and `conda-forge` packages were getting mixed in such that breaks would occur.

**Comment by ericdill** [comment]
sweet. then we can use f-strings!

**Comment by jakirkham** [comment]
Address in PR ( https://github.com/conda-forge/conda-forge-webservices/pull/168 ).
