### ISSUE TITLE
Update CI key should push empty commit?

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge-webservices#171]
Usually when maintainers ask for the CI key to be updated the build is broken. Then they need to either rerun the build or push an empty commit. Can we just push an empty commit for them?

**Comment by jakirkham** [comment]
So we actually don't even need a commit. We can use CircleCI's API to trigger a build.. This should avoid noise for the other CIs as well.

**Comment by jakirkham** [comment]
Also would add that this overlaps with issue ( https://github.com/conda-forge/conda-forge-webservices/issues/107 ) to have commands to restart CIs. Would go so far as to say this is a special subcase of that proposal.

**Comment by beckermr** [comment]
Circle is deprecated / removed. Closing this.
