### ISSUE TITLE
update conda-smithy, conda-forge-pinning when the feedstocks change

### ISSUE THREAD

**Issue by dougalsutherland** [conda-forge/conda-forge-webservices#185]
https://github.com/conda-forge/conda-forge-webservices/pull/183#issuecomment-383133079

Needs to only be triggered once the CircleCI build of whatever new version is up, though. Or else watch for the "out of date" error and update when that happens?

**Comment by jakirkham** [comment]
Would add `conda-build` to this list.

Maybe Heroku can have more than one webhook? That would be the easiest solution.

**Comment by beckermr** [comment]
we have a working cron job that does this now
