### ISSUE TITLE
Linter bot failing PRs with no recipe

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#19]
Seems the linter bot is failing PRs with no recipes. See this as an example ( https://github.com/conda-forge/staged-recipes/pull/371#issuecomment-210562963 ).

Not sure if this was intentional or not. My feeling is this shouldn't be marked as a failure. It makes a maintenance PR, which might be a trivial and possibly essential fix look broken. For someone looking for low hanging fruit to merge or simply skim a large list of PRs, this can steer them away for the wrong reasons.

Personally, I would be happy with no linter status, passing, or possibly pending. The other statuses suggesting something more serious is wrong, which is just simply not accurate in this case.

**Comment by pelson** [comment]
It was intentional, but easy enough to change: https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/linting.py#L128

Just add a elif bad clause and the behaviour will be more akin to your expectations. 

👍

**Comment by jakirkham** [comment]
Yeah I see your point. This definitely a good warning for people that are trying to learn still. That being said, it is a bit noisy for those of us who know that linting is not relevant for say a maintenance PR or similar.

Am now thinking the better solution is have skip commit messages respected instead. See issue ( https://github.com/conda-forge/conda-forge-webservices/issues/46 ) for more details.
