### ISSUE TITLE
Running on deprecated Heroku stack, need to upgrade

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#196]
Saw this warning in a recent Heroku log.

```
 !   Warning: You are running on a deprecated stack.
 !   Please upgrade to the latest stack by following the instructions on:
 !   https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack
```

ref: https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack

**Comment by jakirkham** [comment]
This may be because we are using someone else's buildpack that hasn't been updated in a while. It shouldn't be hard to migrate as we should only be using [this buildpack]( https://github.com/weibeld/heroku-buildpack-run ). It's pretty lightweight. Would also be easy to replace by our own or something very minimal from Heroku.

**Comment by beckermr** [comment]
done with docker

**Comment by jakirkham** [comment]
Indeed. Thanks for all of your work on this 😀
