### ISSUE TITLE
Don't comment if things are still excellent

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge-webservices#2]

**Comment by pelson** [comment]
The service will only add further comments if the situation changes. It will never successively repeat itself: https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/linting.py#L112

**Comment by jakirkham** [comment]
Thanks for adding this.

Though I must say getting these did help me review changes to a recipe as soon as they were pushed. :laughing:

**Comment by jakirkham** [comment]
It looks like this is coming back. See this [comment]( https://github.com/conda-forge/staged-recipes/pull/378#issuecomment-210949296 ) and the one below it.

**Comment by pelson** [comment]
They are different recipes (at least the names are), so I think that is a reasonable thing to re-comment on.
