### ISSUE TITLE
Add details link for CI status

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#20]
This might be tricky. However, if we time it right, this should work. Would be nice to have a "Details" link added to the linter bot's CI status that points to the most recent comment. We should be able to do this in cases where the status has changed. To handle cases where it hasn't, we should read the link from the last status before doing anything and then reuse it in the status for the new commit if nothing has changed.

**Comment by pelson** [comment]
> Would be nice to have a "Details" link added to the linter bot's CI status that points to the most recent comment.

Completely possible - we have all the context we need 👍 
It had crossed my mind, but I got lazy 😄

**Comment by jakirkham** [comment]
No worries. It's not as big of a must have as getting statuses was. That was the real win. :wink:

The rest is just frosting on the cake as far as I'm concerned.
