### ISSUE TITLE
rerender adds back build for unsupported version

### ISSUE THREAD

**Issue by bsipocz** [conda-forge/conda-forge-webservices#201]
For a package that is already python3 only the automated rerender adds back the python2 related builds, that then of course will fail in addition of eating up CI resources unnecessary (e.g. https://github.com/conda-forge/astropy-feedstock/pull/32 or https://github.com/conda-forge/astropy-feedstock/pull/33)

I wonder whether there is any way to control the versions that the rendering will recognize? With quick googling I didn't find anything obvious, but admittedly I'm not familiar with most of the conda-forge tricks.

**Comment by dougalsutherland** [comment]
You should add <code>skip: true&nbsp; # [py2k]</code> to the `build` section of the recipe, rather than manually removing build configs or whatever you did before.
