### ISSUE TITLE
Runaway bots?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#225]
Have some issue with runaway bots in PR ( https://github.com/conda-forge/loky-feedstock/pull/2 ).

**Comment by isuruf** [comment]
This is because of https://github.com/conda-forge/conda-smithy/pull/858. When you change anything in the description, bot is triggered.

**Comment by isuruf** [comment]
Correct link, https://github.com/conda-forge/conda-smithy/pull/851#issuecomment-408418440

**Comment by CJ-Wright** [comment]
I thought the new release fixed this?

**Comment by jakirkham** [comment]
Sounds like it. Somehow wound up with 3.1.9 briefly. We can close.
