### ISSUE TITLE
Improving feedstock webpage listing updates

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#229]
Currently when a recipe is converted at `staged-recipes`, the following actions are taken.

1. Create feedstock
2. Hook in all CIs and webservices (linter, team update, feedstocks updates, commands, etc.)
3. Push changes to the feedstock
  3.a. Run CIs
  3.b. Run team update
  3.c. Run feedstocks
4. Staged-recipes clears converted recipe(s)
5. Staged-recipes triggers feedstock listing webpage update (using feedstocks content)

This mostly works. Though it seems to have gotten a bit slow lately. Also it is a little strange as step 5 depends on step 3.c to be done. However they are not really connected other than they usually happen at different times sequentially. Also they are likely blocked by the same Heroku job, which is forcing them to be sequential.

The main improvement I can think of (though there may be others) is to have completion of run feedstocks trigger the webpage update. This would ensure the two steps that depend on each other are ordered sequential by direct causation as opposed to indirect causation.

However the downside is the webpage list update would be triggered every time the feedstocks are updated. Maybe this ends up not being that bad and we can just live with it. Alternatively we might be able to improve this by detecting additions (as opposed to simply changes) in the feedstock update and only triggering in this event. There may be a similar option for detection the webpage update side, but it's probably best to not get that far if we are wanting to detect additions anyways.

**Comment by beckermr** [comment]
All of the steps for updating the feedstocks webpage content and feedstocks mono-repo are now decoupled from staged-recipes. We also update the webpage using the feedstock-outputs which keeps things synced nicely. Thus I am closing this issue.

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

It is nice to see how far we have come 😄
