### ISSUE TITLE
heroku[web.1]: Error R14 (Memory quota exceeded)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#237]
Seeing lots of errors like this in the Heroku log.

**Comment by beckermr** [comment]
We got a big one of these with the update me endpoint. Rerenders will still cause this. As long as we do not exceed 2x the limit (1 GB) the error is pretty harmless AFAIK.

**Comment by isuruf** [comment]
It's not harmless. Sometimes, the rerender process gets killed.

**Comment by beckermr** [comment]
Oh really? I have not seen it killed unless we go above 1 GB. Good to know!

**Comment by beckermr** [comment]
We could use github actions to rerender by pushing a build to the api.
