### ISSUE TITLE
Frequent timeouts requested

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#238]
Currently we get a lot of timeout errors from the service. Seems like it is slowing down its responsiveness. Would be good to look into the cause and how best to fix this.

**Comment by beckermr** [comment]
We have about 1 per day now.

**Comment by jakirkham** [comment]
So this is still an issue then?

**Comment by beckermr** [comment]
Depends on what you call frequent?

**Comment by beckermr** [comment]
they happen right after the heroku app boots up for the first time and then they go away

**Comment by jakirkham** [comment]
Maybe a new issue then?

**Comment by beckermr** [comment]
sure!

**Comment by jakirkham** [comment]
Thanks! 😄

xref: https://github.com/conda-forge/conda-forge-webservices/issues/346
