### ISSUE TITLE
Background the linting process

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge-webservices#25]
As per the suggestion at https://devcenter.heroku.com/articles/background-jobs-queueing we probably shouldn't be blocking the webservice for the few seconds that it takes to run the linting.

**Comment by jakirkham** [comment]
What is this costing us exactly and how bad will it be to correct?

**Comment by pelson** [comment]
> What is this costing us exactly and how bad will it be to correct?

Shouldn't be hard. I have a hobby dyno which is allowed up to 256 threads and processes, and to my knowledge it is only using one (tornado main loop). It shouldn't be *too* hard to background the processes and use the async stuff in tornado. (you have any experience of this?)

**Comment by jakirkham** [comment]
xref: https://devcenter.heroku.com/articles/python-rq

**Comment by pelson** [comment]
http://stackoverflow.com/questions/22062307/tornado-vs-wsgiwith-gunicorn, http://stackoverflow.com/questions/31245262/cant-run-tornado-app-using-gunicorn and https://groups.google.com/forum/#!topic/python-tornado/tTzZvHaLfb0.

**Comment by beckermr** [comment]
@jakirkham the tornado webserver is now running more than one process, so I think this issue can be closed?

**Comment by jakirkham** [comment]
Ok, feel free to close then.

**Comment by beckermr** [comment]
Yeah so after I sent that message I realized I was wrong. The server is still blocking even though it is multithreaded. So we can do better!

**Comment by jakirkham** [comment]
Thanks for making it better 😄
