### ISSUE TITLE
inconsistent bot reply upon rerender

### ISSUE THREAD

**Issue by carlodri** [conda-forge/conda-forge-webservices#255]
The bot says that there was nothing to re-render, but actually it pushed a re-render commit, see for example https://github.com/conda-forge/msgpack-numpy-feedstock/pull/8

**Comment by jakirkham** [comment]
Thanks @carlodri. Also saw the same thing [here]( https://github.com/conda-forge/qt-feedstock/pull/97#issuecomment-467318930 ) recently.

**Comment by beckermr** [comment]
This should be fixed with github actions rerendering. closing
