### ISSUE TITLE
Use newer conda version (to support compatible release spec)

### ISSUE THREAD

**Issue by hajapy** [conda-forge/conda-forge-webservices#260]
xref: https://github.com/conda-forge/conda-smithy/issues/1075

In short: conda 4.6+ supports `~=` version specifiers, this project uses 4.5 currently (from what I can tell: https://github.com/conda-forge/conda-forge-webservices/blob/master/buildpack-run.sh#L21). I recently contributed two packages that specified their dependencies using `~=` and this caused silent issues such as not being added as a maintainer to the feedstocks after they were built.

**Comment by jakirkham** [comment]
Sounds like a good idea. Would you be willing to submit a PR? 😄

**Comment by beckermr** [comment]
Done. We are on 4.8 now.
