### ISSUE TITLE
Slug size exceeds soft limit of 300 MB

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#261]
Seeing this message in the Heroku build now.

```
Warning: Your slug size (367 MB) exceeds our soft limit (300 MB) which may affect boot time.
```

**Comment by jakirkham** [comment]
This is likely related to the memory issues we are experiencing on Heroku. Cutting out content like static libraries and/or switching to a custom Docker image could help cutdown the image size.

cc @conda-forge/core

**Comment by isuruf** [comment]
> This is likely related to the memory issues we are experiencing on Heroku.

Why do you think slug size affects memory issues?

**Comment by jakirkham** [comment]
Because we have encountered this problem before and decreasing slug size helped.

**Comment by jakirkham** [comment]
From the ["Known issues and limitations" section of "Building Docker Images with heroku.yml"]( https://devcenter.heroku.com/articles/build-docker-images-heroku-yml#known-issues-and-limitations ):

> ...Docker images are not subject to size restrictions (unlike [slugs]( https://devcenter.heroku.com/articles/limits#slug-size ))...

> ...they are subject to the [dyno boot time restriction]( https://devcenter.heroku.com/articles/limits#boot-timeout ).

**Comment by jakirkham** [comment]
Solved by PR ( https://github.com/conda-forge/conda-forge-webservices/pull/304 ). Thanks @beckermr! 😄
