### ISSUE TITLE
Re-render PR missing "fixes" keyword with issue

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#262]
Noticed PR ( https://github.com/conda-forge/billiard-feedstock/pull/25 ) was missing the "Fixes #x" line. This helps autoclose the associated issue on merge. Would be great to readd that text.

**Comment by scopatz** [comment]
:+1: That would be nice

**Comment by jakirkham** [comment]
Solved in PR ( https://github.com/conda-forge/conda-forge-webservices/pull/175 ).
