### ISSUE TITLE
add test of new CI restart command

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#268]
The new CI restart comment needs tests.

**Comment by jakirkham** [comment]
cc @isuruf

**Comment by jakirkham** [comment]
What do we want to test here? That the text matches?

**Comment by beckermr** [comment]
I’ll need to look at the test file. I’ve used the command already and it works great, so functionally we are all set.

**Comment by isuruf** [comment]
We can test that PR was closed and then opened by mocking which is what other tests do.

**Comment by beckermr** [comment]
Standard things would be to mock out the api object and make sure it is called correctly.

**Comment by jakirkham** [comment]
Do we want to stick with open/close as the way to restart PRs long term? Asking as this may confuse the regro bot. If not, maybe we shouldn’t worry about testing that part.

**Comment by beckermr** [comment]
I agree it may confuse the bot. A more complete solution would involve the apis of more than one ci provider. I think for now we live with this until we have energy to do something better.

**Comment by jakirkham** [comment]
Sure. My point is we probably don’t need to tailor the tests closely to this implementation if we plan to change it later.

**Comment by beckermr** [comment]
I made a PR against this issue last night, but no need to merge it. I'll leave it to @isuruf and @jakirkham to sort it out.

**Comment by beckermr** [comment]
I'm closing this for now. Feel free to reopen!
