### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#27]
Seems we don't have a license here, but there is some interest in potentially using the code. Guessing this is BSD 3-Clause as is the norm in conda-forge or are there thoughts on it being something else?

cc @pelson @ocefpaf @astrofrog

**Comment by pelson** [comment]
Confirming the code is BSD 3-clause.

**Comment by jakirkham** [comment]
Adding a license file in this PR ( https://github.com/conda-forge/conda-forge-webservices/pull/28 ).
