### ISSUE TITLE
ENH add command to bump the team of a feedstock/staged-recipes

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#278]
We should add a command `@conda-forge-admin, please bump the team` so that people who are not in conda-forge can bump the staged recipes team and other teams on feedstocks.

**Comment by chrisburr** [comment]
Copied from #279:
> As only members of the organisation can ping the teams it would be useful to have a command to ping the teams. Potential examples:
> 
> - `@conda-forge-admin, please ping team`
> - `@conda-forge-admin, please ping $NAME_OF_TEAM`
> - `@conda-forge-admin, please ping core`

**Comment by beckermr** [comment]
Yes, `@conda-forge-admin, please ping team` is much better. I would just implement this variant and call it good. No reason to give people more ways to bother core. ;p

**Comment by jakirkham** [comment]
Or even `please help` or `please review`. 🙂
