### ISSUE TITLE
TST automatically skip tests that require a github API key

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#285]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by isuruf** [comment]
But then people will start merging PRs without pushing the branch to the main repo.

**Comment by beckermr** [comment]
Sure that might be a problem. Happy to close this!
