### ISSUE TITLE
Push to autotick bot graph when PR is closed/merged/bot-rerun

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge-webservices#289]
It would be great if the webservices could write to the bot's graph when a PR is closed/merged or has a bot-rerun put against it (bonus points for reopened). This will fix the bot's lackluster updating of the graph which is causing headaches around bot-rerun and migrations.

This requires:
1. shallow clone the graph
2. when PR meets criteria update graph's pr_json for that PR
3. push graph back up
4. pull graph for any updates
5. permissions for pushing to the graph

**Comment by beckermr** [comment]
With the new dynamodb instance, this issue should be an easy thing to do. We'll need some keys, but after that, the database will take care of the associated issues around updates.

**Comment by jakirkham** [comment]
Would you be able to sketch out what this work would look like?

**Comment by beckermr** [comment]
Basically, the bot would watch for closed PRs that have been merged on feedstocks. If it finds one, it would push the PR json blob up to the dynamodb instance.

**Comment by beckermr** [comment]
You can use boto3 to upsert the data in the right spot.

**Comment by jakirkham** [comment]
Probably worth creating a separate webhook and handler for it.

**Comment by beckermr** [comment]
@lguo52 If we do ever have the PR json in a real database, then we might be able to address this issue.
