### ISSUE TITLE
Add an hourly cron job to ping the `update_me` URL

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-webservices#299]
This would make the rerendering failures due to new conda-smithy or conda-forge-pinning go away inside an hour.

**Comment by beckermr** [comment]
Actually, I’d be better to add a webhook to the conda forge pinnings feedstock and the conda build feedstock to bump this endpoint.

**Comment by beckermr** [comment]
This will avoid rebuilding the webservice too much and the associated potential downtime.

**Comment by isuruf** [comment]
> Actually, I’d be better to add a webhook to the conda forge pinnings feedstock and the conda build feedstock to bump this endpoint.

There is one already, but the CDN update takes time.

> This will avoid rebuilding the webservice too much and the associated potential downtime.

There is code to not rebuilding webservice if not necessary.

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/update_me.py#L14-L30

**Comment by beckermr** [comment]
Ahhhhhhh ok. Then let's make a cron job in circle!

**Comment by beckermr** [comment]
I'm like 99% sure the updateme hook has never worked due to this bug:

https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/webapp.py#L32
