### ISSUE TITLE
update me endpoint spikes memory usage

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#311]
It appears the update me endpoint is spiking memory usage.

**Comment by beckermr** [comment]
cc @isuruf

**Comment by jakirkham** [comment]
IIUC we are performing a solve to see if updating its needed. We could forgo that check and just redeploy every hour. What do we think?

**Comment by isuruf** [comment]
The webapp will be down for a minute or two every hour then and important requests like update team might get dropped.

**Comment by jakirkham** [comment]
Doesn't redeployment happen orthogonally to restarting the webservice? How long does it take for the Docker container to start?

If the resources needed for updating are prohibitive, it seems reasonable to consider alternatives. What else would you propose?

**Comment by beckermr** [comment]
Putting the solve in a subprocess per @isuruf’s suggestion is very straight forward and would solve the memory issues. I think this is the best option.

**Comment by beckermr** [comment]
The lag in redeployment is only the time to start the docker container fwiw
