### ISSUE TITLE
Check if the status endpoint is still needed

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#316]
There have been some changes to the status page. It would be good to see if the [status endpoint]( https://github.com/conda-forge/conda-forge-webservices/blob/4bff8cf9351e8b5cc259d9e72b4e1dc1ac9228f2/conda_forge_webservices/webapp.py#L183 ) and [status script]( https://github.com/conda-forge/conda-forge-webservices/blob/4bff8cf9351e8b5cc259d9e72b4e1dc1ac9228f2/conda_forge_webservices/status.py ) are still needed. If not, it would be reasonable to drop them.

cc @beckermr

**Comment by beckermr** [comment]
We should move the status repo to GitHub actions and remove the end point yes.

**Comment by beckermr** [comment]
I think we do want the ability to post messages there for specific issues but we don’t need to maintain that here.
