### ISSUE TITLE
better updates when rerendering fails

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#319]
Right now, we use an hourly cron job to test if core dependencies like conda / conda-build / conda-smithy / conda-forge-pinning have changed. This causes the bot to be failing for extended periods of time. We had hooks but they fail due to the CDN. We need to shorten this delay or somehow update the packages on the fly.

**Comment by beckermr** [comment]
cc @isuruf

**Comment by jakirkham** [comment]
Some thoughts:

* Could we offload some of this deployment work to CI?
* Would it be possible to derive some or all of our image from `condaforge/linux-anvil-comp7`?

Maybe these would reduce our load on CI?

**Comment by beckermr** [comment]
The docker image is not a load on the heroku instance IIUIC. heroku builds it and then deploys it. The current cron hook will kick this process once an hour if and only if the dependencies have changed. 

The issue is that checking if the dependencies have changed currently pushes the bot's memory usage well above 500 MB. If we could fix that and make the checking process faster, then it would be straight forward to basically kick the bot more often to check.

**Comment by beckermr** [comment]
this is solved by moving the rendering to github actions.
