### ISSUE TITLE
appveyor config updates

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#320]
We have a lot of appveyor configuration errors where the settings are wrong or projects have duplicate registration. A command that let's people instruct the bot to clean that up is probably a good thing.

**Comment by beckermr** [comment]
cc @isuruf

**Comment by isuruf** [comment]
I deleted all duplicate registrations a few days ago. (I sent 5000 requests per hour which meant 1000 feedstocks per hour to find duplicates.)
Fixing the settings can be done as a long running process.

**Comment by beckermr** [comment]
Ahh ok. I am seeing repos with wrong settings still so I guess we should kick that process off and close this.
