### ISSUE TITLE
lint bot thinks feedstock with custom recipe_dir is in staged-recipes?

### ISSUE THREAD

**Issue by timsnyder** [conda-forge/conda-forge-webservices#342]
Issue:

I'm cleaning up some stuff in conda_smithy that assumes `recipe_dir` is 'recipe'.  While [testing in an actual feedstock](https://github.com/conda-forge/make-feedstock/pull/22#issuecomment-598498016), the linter fails because:
![image](https://user-images.githubusercontent.com/83846/76581046-06cf1100-64a0-11ea-9c0a-27068e215739.png)

Without digging into the lint-bot code, it seems like it may be assuming that recipe is in staged-recipes if the last element of the recipe directory isn't 'recipe'.  I'm guessing here only based on `conda smithy recipe-lint conda.recipe` passing fine when I run it locally.

If this is intended because the lint bot wants all conda-forge org feedstocks to have recipe_dir=='recipe', feel free to close this out.

**Comment by isuruf** [comment]
It's not intended, but this lint is a conda-forge specific one that needs to be enabled explicitly and all feedstocks in conda-forge have `recipe` as `recipe_dir`. So, if you are using the linter outside of conda-forge, it wouldn't raise this lint.

**Comment by timsnyder** [comment]
That's what I thought.  I just wanted to mention it because I'm not sure if other orgs like bioconda try to reuse stuff out of conda-forge-webservices and might encounter this.  At the moment, I'm not trying to reuse the linting bot.  And I'm fine with this issue being left open or closed if it is definitely outside the scope of the lint bot.

**Comment by beckermr** [comment]
The lint bot is totally custom to conda forge afaict. I’d say this issue is well out of scope. Thus I am going to close it.
