### ISSUE TITLE
ping any team

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge-webservices#354]
It would be super helpful if users could ask the bot to ping any team (for instance with the help teams, or have the bot ping the associated team when moving pins)

**Comment by beckermr** [comment]
That should already work. What do you mean?

I did notice that the pinning PRs don’t seem to ping the team like they should. Is that what you mean?

**Comment by CJ-Wright** [comment]
Yes, and I think the ping is only for the team associated with the repo

**Comment by CJ-Wright** [comment]
Also the regex isn't correct for arb. teams https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/commands.py#L31

**Comment by beckermr** [comment]
Yup I noticed that about an hour ago. Will fix!

**Comment by beckermr** [comment]
Should be fixed now? Give the webservice ~20 minutes to redeploy
