### ISSUE TITLE
Restart ci command not working for drone

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#396]
It appears that drone no longer responds to opening and closing the pr by restarting the job. We'll need to make an api call likely.

**Comment by jakirkham** [comment]
Well we are also having issues with Azure. Plus GitHub earlier mentioned a degradation issue (though they have since marked it resolved). Some related discussion in issue ( https://github.com/conda-forge/conda-build-feedstock/pull/140 ). Wouldn't be surprised if GitHub is still having issues though.

**Comment by mbargull** [comment]
Yeah, I noticed Drone didn't rerun even with this empty commit: https://github.com/conda-forge/conda-build-feedstock/pull/140/commits/5217f049fb61fcd3b679fbd53d74adaaa86c8ac3
Had to add a whitespace change to trigger it.
I agree with John. Looks like GitHub isn't triggering CIs properly.

**Comment by beckermr** [comment]
This has been going on for months. I just finally got around to making an issue for it.

**Comment by mbargull** [comment]
> going on for months

Oh, that's nice! /s

----
(OT then: Did you by any chance notice Azure hiccups recently?)

**Comment by beckermr** [comment]
Yes I did. Not sure what we can do about that. Seems intermittent.

**Comment by jakirkham** [comment]
I wonder if we can just a GitHub API for all of them (given CI checks are getting more closely connected with GitHub).

**Comment by beckermr** [comment]
I think azure lacked the api before. Might have changed. We can add a call for drone though.

**Comment by jakirkham** [comment]
I'm thinking we can just restart all builds through [this GitHub API]( https://docs.github.com/en/rest/reference/checks#rerequest-a-check-suite ).

**Comment by beckermr** [comment]
Drone uses webhooks, not this api
