### ISSUE TITLE
make code for team updates more robust

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#426]
We need handle weird spacing issues properly. It got fooled by a recipe that had ` extra:` instead of `extra:`.

**Comment by jakirkham** [comment]
Are we using a YAML parser currently?

**Comment by beckermr** [comment]
We had to do some odd optimizations. I think I fixed it for now.

**Comment by jakirkham** [comment]
Yeah that's what I'm wondering about. We use to need these things. Maybe we don't need them any more now (though not exactly that new) that Conda-Build provides a public API for parsing recipes.

**Comment by beckermr** [comment]
The conda-build api is a bit slow for this so we do a quick thing that parses faster: 

```
    skip = 0
    for line in resp.decoded_content.decode("utf-8").splitlines():
        if line.strip().startswith("extra:"):
            skip += 1
        if skip > 0:
            keep_lines.append(line)
    assert skip == 1, "team update failed due to > 1 'extra:' sections"
```


see https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/update_teams.py#L59
