### ISSUE TITLE
Auto raise infrastructure issues on status page

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#44]
It might be worth auto-raising issues on the status page if there are issues on associated infrastructure providers' status pages.

All of them support feeds (Atom and RSS). Though we could ask if others would support it, this may come at some cost to the infrastructure provider. In any event, we should be able to convert the feeds from the associated services' status pages with some sort of PubSubHubbub to webhooks, which we can plug right in to Heroku. Refs for the status pages and PubSubHubbub providers below.

CIs
- Travis CI - https://www.traviscistatus.com
- CircleCI - http://status.circleci.com
- AppVeyor - http://status.appveyor.com

Docker Hub and Quay
- Quay - http://status.quay.io/
- Docker http://status.docker.com/

Not sure if there is one for Anaconda, but maybe that is worth asking for.

PubSubHubbub Services
- Google - https://pubsubhubbub.appspot.com/
- Superfeedr - https://pubsubhubbub.superfeedr.com/

**Comment by beckermr** [comment]
This is done in the status repo now via javascript. Shall we close @jakirkham?

**Comment by jakirkham** [comment]
Thanks for all the hard work! Yes please. Feel free to take the honors 😄
