### ISSUE TITLE
add user service doesn't skip ci

### ISSUE THREAD

**Issue by izahn** [conda-forge/conda-forge-webservices#486]
I opened https://github.com/conda-forge/octave-feedstock/issues/60 which triggered https://github.com/conda-forge/octave-feedstock/pull/61 as expected. However, https://github.com/conda-forge/octave-feedstock/pull/61 triggered CI rebuild, which is not expected. Maybe it needs `[skip ci]` instead of (or in addition to) `[ci skip]`?

**Comment by beckermr** [comment]
This is azure not honoring ci skip for PR builds only. It works on builds in the main repo.

**Comment by izahn** [comment]
Hmm, so this is expected? I thought I remembered that this used to actually skip the ci checks. Ah well, sorry for the noise.
