### ISSUE TITLE
Feature request: notification on CDN availablility

### ISSUE THREAD

**Issue by maresb** [conda-forge/conda-forge-webservices#490]
I keep thinking that it would be really convenient if one could write something like `@conda-forge-admin, please notify when available`, which would post a message to a feedstock PR when the corresponding build becomes available on the CDN.

Has this been discussed before, and would this be the correct repo to implement a PR?

**Comment by beckermr** [comment]
Given how short the CDN delay is these days, I don't think this one is worth it. Shall we close?

**Comment by jakirkham** [comment]
CDN updates are [~10mins]( https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-anaconda-delay ). This seems safely within "the grab a cup of coffee" window :)

That said, there might be more general value in say subscribing to package updates for particular packages one cares about. Raised an issue ( https://github.com/conda/infra/issues/670 ), but it probably needs a bit more refinement and help from someone familiar with the CDN.
