### ISSUE TITLE
updates of feedstocks repo failing due to master to main migration

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#491]
The feedstocks submodule updates are failing due to missing master branches.  IDK how to fix yet. As this repo is not used for much internally, I'm going to keep going and go back and fix later.

cc @conda-forge/core

**Comment by jakirkham** [comment]
Do you have a log with the failure?

**Comment by beckermr** [comment]
No but the docs are pretty clear. 

We need to update the branch in gitmodules and then call the correct commands via git. 

I think we can use gitpython but I have not worked out the commands.
