### ISSUE TITLE
Using `libmamba` solver for re-rendering

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#502]
For some things like re-rendering (particularly slower ones), switching to the `libmamba` solver might be quite valuable to speed up re-rendering.

xref: https://github.com/conda-forge/conda-smithy/issues/1307

**Comment by jaimergp** [comment]
This is now the default in conda-build for a while, so I think it's safe to close. Reopen if I'm wrong 😬
