### ISSUE TITLE
Persistent upload failure

### ISSUE THREAD

**Issue by tdegeus** [conda-forge/conda-forge-webservices#549]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

See https://github.com/conda-forge/perl-extutils-makemaker-feedstock/issues/5 .

I have tried to reset the token https://github.com/conda-forge/admin-requests/pull/691 and tried several times after, each time with the same outcome

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by isuruf** [comment]
It looks like things got uploaded to `conda-forge` from `cf-staging`, but the copy in `cf-staging` was not deleted yet. I deleted it manually.

**Comment by tdegeus** [comment]
Thanks! So all is good?

**Comment by isuruf** [comment]
Should be. Open a new issue if it occurs again.
