### ISSUE TITLE
rebuild docker images when versions change

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#578]
Right now we redeploy the webservices when smithy gets an update so that we get the latest linting. We should use a repo dispatch event to rebuild our docker images for automerge and rerendering using the same trigger. We'll need to add the pinnings repo, conda-build, boa, conda, and mamba to the list of packages used to trigger an update.

**Comment by beckermr** [comment]
cc @mbargull 

see this workflow: https://github.com/conda-forge/conda-forge-webservices/actions/workflows/clean-and-update.yml

We probably want a higher cadence if this is going to be used for pinnings. 

We can also just update the pinnings in the rerendering job which may be faster.

**Comment by beckermr** [comment]
@mbargull thinks updating in the job is wasteful and says we should rebuild the docker image more often.

I am happy either way so i'll leave it to you two to work out.

**Comment by jakirkham** [comment]
If we were willing to do a daily redeploy (off hours), that would be great!

Unfortunately when I've raised this idea in the past, have gotten push back from others that it is too frequent

The pinning repo pushes out packages multiple times per day (and some of those changes don't even update the pinnings). So that seems at odds with the concern raised above

**Comment by mbargull** [comment]
Thanks @beckermr!
@jakirkham, the context is the discussion at https://github.com/conda-forge/webservices-dispatch-action/pull/57#pullrequestreview-1952337509 , talking about the `webservices-dispatch-action` image.
Essentially, the thing is that we have an `conda update --all` in the entrypoint of the `webservices-dispatch-action` image which means that we run this `conda update --all` every single time someone asks the bot to rerender a feedstock; if we update the image for every single release of `conda-forge-pinning` etc., we can omit this `conda update --all` (since we're already up-to-date) and in sum use less resources overall (reasonable assumption: "number of rerender comments" considerably greater than "number of updates to `conda-forge-pinning` etc.")

**Comment by beckermr** [comment]
Yes @jakirkham @mbargull very sorry if I have given either of you push back on these items in the past and am saying different things now.

**Comment by beckermr** [comment]
> Would it make sense to have a cron job here? IOW redeploy weekly (like we do elsewhere)

Yes we have an hourly cronjob here that pushes a commit if it needs to.

**Comment by jakirkham** [comment]
If the concern is the `conda update --all`, would it make sense to just replace that line with `conda update conda-forge-pinning` and the changes Matt outlined above?

**Comment by mbargull** [comment]
IDK whether we had discussions about the `webservices-dispatch-action` update cadence before.
(I know we had discussions about updating the build images (`linux-anvil-....` stuff) more often and inclusion of compilers and whatnot ; but that's not what I wanted to touch.)
Can't remember you pushing back on things either way ;D.

**Comment by beckermr** [comment]
> If the concern is the conda update --all, would it make sense to just replace that line with conda update conda-forge-pinning and the changes Matt outlined above?

So both commands take about 10s to download/unpack repodata and do the solve on my machine. I did not run the installs, but we can expect `--all` to do more downloading. My guess is that we'll save a little time this way, but it won't be overwhelming.

**Comment by mbargull** [comment]
> If the concern is the `conda update --all`, would it make sense to just replace that line with `conda update conda-forge-pinning` and the changes Matt outlined above?

No, it's generally unnecessary to have any `conda update` there if we can avoid it in a centralized place beforehand, IMO.
Take, e.g., https://github.com/conda-forge/pymbar-feedstock/actions/runs/8379159325/job/22945403658 which takes about 30 seconds for a very small update.

**Comment by mbargull** [comment]
> > If the concern is the conda update --all, would it make sense to just replace that line with conda update conda-forge-pinning and the changes Matt outlined above?
> 
> So both commands take about 10s to download/unpack repodata and do the solve on my machine. I did not run the installs, but we can expect `--all` to do more downloading. My guess is that we'll save a little time this way, but it won't be overwhelming.

It really depends on what has been updated since the image has been built; in some cases it might even take a minute.
But even 10s (expect CI to be slower than your machine) is much when we consider this is multiplied by the times people issue "conda-forge-admin, please rerender".

**Comment by jakirkham** [comment]
Tbh we probably can just drop the `conda update --all`

As `conda-smithy` already fetches the latest `conda-forge-pinning` anyways

That all being said, I may have missed it, but what problem are we trying to solve here? Just need a little more clarity on our goal

**Comment by beckermr** [comment]
We were trying to solve how to keep the container up to date without the call to conda update. However, I forgot that smithy pulls the pinnings by hand so probably we can just remove that line as you say.

**Comment by mbargull** [comment]
Ah, right, makes sense.
So, it'll just be updating the image for new `conda`/`conda-build`/`conda-smithy` builds which are not as often and usually not as time-critical (and could, if needed, be handled by simple manual workflow dispatch).

**Comment by beckermr** [comment]
OK. I think the consensus is that we can remove the update line and given the sparse release cycles of smithy, etc., we can add the repo dispatch here or not. 

I will add the repo dispatch here in the spirit of excessive automation that imbues everything we do here at conda-forge.
