### ISSUE TITLE
Team update/feedstocks update webservice

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#63]
While we have done a good job at limited the effect of these scripts, there are still problems. If they haven't surfaced or resurfaced yet, they will soon. So we should start planning to handle them. Here are some issues that come to mind.
1. Scales poorly
   1. GitHub Rate limit issues.
      1. https://github.com/conda-forge/conda-forge.github.io/issues/88
      2. https://github.com/conda-forge/conda-forge.github.io/issues/172
2. Fragile
   1. Feedstock level issues break it.
      1. https://github.com/conda-forge/conda-forge.github.io/issues/86
      2. https://github.com/conda-forge/conda-forge.github.io/issues/139
      3. https://github.com/conda-forge/conda-forge.github.io/issues/228
3. Inefficient
   1. Disproportional time spent on unchanged feedstocks. ( https://github.com/conda-forge/conda-forge.github.io/issues/88#issuecomment-217548992 )
   2. Run time increased from 2min to 12min in last 6mos.
4. Lagged response
   1. User are frequently surprised they aren't added right away.
      1.1. Recent example ( https://github.com/conda-forge/traitlets-feedstock/pull/5#issuecomment-245930774 ), but there are many.
5. Duplicated functionality.
   1. staged-recipes - https://github.com/conda-forge/staged-recipes/pull/733
   2. webpage repo - https://github.com/conda-forge/conda-forge.github.io/pull/15
6. Poor separation of concerns
   1. Run in CI on webpage repo.
   2. Run on PR merges that consist of...
      1. Minutes
      2. Pinnings
      3. Assorted helper scripts
7. Lacking test coverage

Looking at these issues they are all directly or indirectly because we have been using a global update script. As a result, we are spending lots of time doing work that is not particularly useful and paying a high price for it. However, when going back through the feedstocks repo (which is updated roughly once daily), it looks like ~20 feedstocks are added/changed daily. So there is no reason it should be so difficult to keep up with this especially as often as people want us to for cheap. What can we do?

---

We need to switch from global update to asynchronous local updates. This model has been highly successful for us with things like the linter. To solve this particular problem, we would need a webservice that listens to [`PushEvents`](https://developer.github.com/v3/activity/events/types/#pushevent) on each feedstock. When there is a push event, we do the following.
1. New repos: `conda-smithy` adds webhook for this service (just like the linter).
2. Update the sha of the feedstock in the feedstocks repo.
3. Get the list of GitHub teams.
4. Add (if not present)/Get the `all-members` and `<feedstock>` teams.
5. Get the member lists for both teams.
6. Compare our maintainers list to both team list.
7. Add any members that are not present to both teams.

All of this is actually pretty fast to run through.

By working only with feedstocks that see updates, we no longer are scaling by number of feedstocks, but are scaling by number of active feedstocks, which is much better behaved. Even if there is a lot of activity our GitHub API usage for each feedstock is quite low (well below the rate limit). As far as the feedstocks repo, we are only updating one feedstock at a time. So this significantly cuts down time spent cloning or trying to clone feedstocks.

As pushes are localized to each feedstock, issues with one feedstock and the service don't effect another feedstock's ability to use the service. This makes it more resilient and easier to pinpoint where issues are. It also avoids having team updates blocked for the org by issues with one feedstock. Further if there are issues with a feedstock, they are easy to localize and start working on immediately. GitHub API limits will not play a significant role in blocking progress testing fixes.

Further no time is spent on feedstocks that are not updated. Only feedstocks that are being getting pushes (directly or via merges) are analyzed for changes. This already makes things massively more efficient. We haven't even begun to discuss optimizations. For instance, we could further cutdown our GitHub API rate limit by looking at the maintainer's list before and after each push. Still I think it will be awhile before we need to give that serious thought.

As this works on each push, there is no lag in the process. Teams are created/updated immediately. This improves the user experience by giving them immediate feedback. Also it helps more quickly find issues with the service. If someone is not added immediately, there is a service problem that needs to be investigated. It also cuts down on notifications of false positives.

Code snippets from the webpage repo/staged-recipes can be used to fill this out. Also `conda-smithy` would learn how to add the webhook for this service. Once all of this is done, neither place needs to know about how to handle team creation or updates. Further there is no special case for creating a new feedstock vs. updating an existing one as all pushes trigger it just the same.

Additionally by moving the code to manage these updates here, not only will they not need to live at the webpage repo, but they won't need to be triggered by the webpage repo. This will avoid many spurious failures at the webpage repo due to GitHub API rate limits or other issues with the update scripts that are largely orthogonal to the PRs being added there. The freed up CI resource can then be used for testing other scripts or another purpose. 

Finally as doing this will give us a simple service that runs here, we will be in much better shape for testing. The test infrastructure here is well suited for working with the GitHub API. There may be some tricks required in order to get pushes or mock pushes. Still we already have a good system for testing different branches and reporting what was found. It may take a bit of work to get good coverage, but we should be able to get some coverage to start.

In short, setting up a webservice to manage team and feedstock updates is a clear winner because it moves from a global update model to a local update model.

**Comment by pelson** [comment]
Thanks @jakirkham (*very* thorough :wink:). I completely agree. Question is - can we generalise so that we can share such a capability beyond conda-forge and thus tap into more potential maintainers?

**Comment by jakirkham** [comment]
Depends on what you mean by share beyond conda-forge. 😄 What did you have in mind?

**Comment by jakirkham** [comment]
Also cc-ing @ericdill given our bonding over the problems the current strategy will run into.

**Comment by pelson** [comment]
I forgot to mention, some months ago I started re-writing the team script so that it only updated teams that had had a git commit in the last N days (I think I defaulted to 2 or something). That does dramatically reduce the burden on the team management, and even if we do have a per-feedstock service, we are still going to be able to want to run a script for those teams that got missed out (e.g. through service downtime).

**Comment by jakirkham** [comment]
Sorry will respond to that comment later just want to make a note that we need to handle deletion events too.

**Comment by jakirkham** [comment]
TBH it isn't even so much the number of feedstocks updated, but how fragile the script is to any issue that might occur in the feedstock or its recipe. Here is a [recent breakage]( https://github.com/conda-forge/pytools-feedstock/commit/a9457506b924bb1aa3a57bac87f1f0b402afdd9f#commitcomment-19371165 ). Now I understand breakage will happen, but I would rather contain it to the feedstock that causes the issue. If we do still have a global update script, maybe it can just retrigger the webhooks on each feedstocks to this service instead. That way there are fewer vulnerabilities in the loop itself. Plus there is less code duplication that way.

**Comment by jakirkham** [comment]
We are starting to run into somewhat frequent GitHub rate limiting when running the team update script. So it is time to start implementing something so as to move away from that strategy of doing team updates.

**Comment by jakirkham** [comment]
@conda-forge/core, could you please take a look at this proposal? The team update script is struggling to keep up with the growth of conda-forge. So this proposal lays out how to handle team updates on this large scale.

**Comment by jakirkham** [comment]
The team update portion is now available for recent feedstocks (created with `conda-smithy` 2.4.0) thanks to the heroic efforts of @isuruf. At this point, it is a matter of rolling this feature out to all of the legacy feedstocks as well.

**Comment by jakirkham** [comment]
Last piece is in PR ( https://github.com/conda-forge/conda-forge-webservices/pull/115 ).
