### ISSUE TITLE
Use conda_forge_metadata.fetch_allowed_autoreg_feedstock_globs here

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-webservices#668]
Instead of https://github.com/conda-forge/conda-forge-webservices/blob/7ea31d39c8df57f0ad2a42aa63f37685e543c9ae/conda_forge_webservices/feedstock_outputs.py#L34-L46

**Comment by beckermr** [comment]
I have a PR up for this that does that but simplifies further:  https://github.com/conda-forge/conda-forge-webservices/pull/669
