### ISSUE TITLE
Squash Docker image?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#707]
Noticed this image has quite a few layers. This can add to the time to pull the image. Noting this since each bot operation pulls the image

Am wondering if we can do something to consolidate the image layers. For example in `docker-images` we enabled squash ( https://github.com/conda-forge/docker-images/pull/99 ), which helped address a similar problem with those images. Am wondering if we could apply a similar approach here

**Comment by beckermr** [comment]
@jakirkham the current `docker/build-push-action` doesn't support squash so we'd have to move to doing everything at the CLI, but it should be possible.

**Comment by beckermr** [comment]
@jakirkham Are you sure the docker images in conda-forge/docker-images are being squashed? I see it pushing multiple layers in the CI logs.

**Comment by beckermr** [comment]
yeah squash is dead: https://stackoverflow.com/questions/41764336/how-does-the-new-docker-squash-work

**Comment by beckermr** [comment]
I am trying the 3rd party `docker-squash` tool.

**Comment by beckermr** [comment]
This tool produces buggy images, so not the way to go for sure.

**Comment by jakirkham** [comment]
Catching up. Hold please 😅 

> Yes but this image has moved to conda-forge-webservices.

Oh! I see [`webservices-dispatch-action`]( https://github.com/conda-forge/webservices-dispatch-action ) was archived hours ago. Meant to open an issue for both, but yeah may not be up-to-date on where we build this image (especially after all the recent updates. Thank you! 🙏)

> Are you sure the docker images in conda-forge/docker-images are being squashed? I see it pushing multiple layers in the CI logs.

Yeah we [pass squash]( https://github.com/conda-forge/docker-images/blob/6d30f8fc76d5542a15330112f5b705bcc78b1887/.github/workflows/ci.yaml#L308 ). There are still layers from parent images, but those are unaffected by this flag

> yeah squash is dead: https://stackoverflow.com/questions/41764336/how-does-the-new-docker-squash-work

😢 Honestly I don't get it

> I am trying the 3rd party docker-squash tool.
> This tool produces buggy images, so not the way to go for sure.

Maybe we just need to condense steps. Do more in one `RUN` or other command

Which `Dockerfile` should we be looking at?

**Comment by beckermr** [comment]
The dockerfile is the one that ends with _wda.
