### ISSUE TITLE
Re-rendering bot doesn't report lack of write permissions?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#708]
Asked the bot recent to try re-render a few times in PR ( https://github.com/conda-forge/nsight-compute-feedstock/pull/22 ). However each time the bot was unable to. Though it did not report that we lacked edit permissions ( https://github.com/conda-forge/nsight-compute-feedstock/pull/22#issuecomment-2109415752 )

Did something change about how the bot raises this information? Or is there more going on here that we are missing?

**Comment by beckermr** [comment]
closing this since we no longer have this issue.

**Comment by jakirkham** [comment]
Thanks Matt! 🙏
