### ISSUE TITLE
Fix formatting/style of status page

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#71]
Suggestion from @pelson that we clean up formatting/style of the status page. This is a catch all issue for that discussion ATM. Feel free to edit/add items to the list in this OP or ask that they be added
- [ ] Maybe include standard navigation bar from home page.
- [ ] Tweak color scheme
- [ ] Change background
- [x] Fix logo/icon ( PR https://github.com/conda-forge/status/pull/28 )

**Comment by jakirkham** [comment]
Some of these are not easy to change as there are no setting yet to do so. Will ask upstream about the navigation bar. Will likely skip the rest and let those with a burning desire pursue them.

**Comment by beckermr** [comment]
The status page has had a total revamp that has addressed these issues. Closing.
