### ISSUE TITLE
Automated Welcome Message

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#73]
@jakirkham commented on [Fri May 20 2016](https://github.com/conda-forge/conda-forge.github.io/issues/149)

This is an idea that @ericdill had (or at least similar to it). I used to do these things by hand, but with the growth of conda-forge. It is a bit hard to stay on top of this and I don't think I am the only one that feels that way. Would be nice to have a bot message that welcomes new people added as maintainers to conda-forge when a PR at staged-recipes is merged. The bot would need to explain the following things:
1. Briefly what [`conda`](http://conda.pydata.org/) is.
2. Briefly what [conda-forge](http://conda-forge.github.io/) is.
3. Briefly what a feedstocks is and which ones will be created.
4. Point out an invite to conda-forge is being sent to them and what that entails.
5. Explain how to download packages from [`conda-forge`](http://anaconda.org/conda-forge/).
6. Explain how to make changes to their feedstocks (fork, branch in fork, PR to main).

While 1 may sound silly, there have been a few people that have joined that never heard of `conda`. So, explaining what it is helps. Similarly 2 is nice as people may have been asked to help maintain, but may only now be figuring out what conda-forge is. Guessing 3-6 don't need justification, but could be wrong. Thoughts would be appreciated.

Note: There was another idea about inviting devs of a package. Unfortunately, that problem can be a bit ill-defined at times (e.g. source not on GitHub). Still that might be worth thinking about.

---

@jakirkham commented on [Tue Sep 13 2016](https://github.com/conda-forge/conda-forge.github.io/issues/149#issuecomment-246705763)

This should be more easily achievable if we convert the team update script to a webservice as described in issue ( https://github.com/conda-forge/conda-forge-webservices/issues/63 ).

---

@jakirkham commented on [Tue Sep 20 2016](https://github.com/conda-forge/conda-forge.github.io/issues/149#issuecomment-247866869)

Template message below.

> Soon you should get an email that invite you to join conda-forge, <GitHub handles>. Once accepted you will be added to a team with the same name as this recipe. Those will give you permissions on the feedstock (repo) for this recipe.
> 
> Make sure when proposing any change that you go through the typical GitHub workflow of forking the feedstock and making changes in your fork that you PR back. Once merged CIs will build and deploy any changes you make.
> 
> Please let us know if you have any questions and welcome to conda-forge. :)

---

@jakirkham commented on [Sun Sep 25 2016](https://github.com/conda-forge/conda-forge.github.io/issues/149#issuecomment-249471119)

Going to kick this over the webservices repo.

**Comment by jakirkham** [comment]
Any thoughts on this, @isuruf?

**Comment by isuruf** [comment]
I started a PR here, https://github.com/conda-forge/conda-smithy/pull/565. It'd be great if you can finish it

**Comment by jakirkham** [comment]
Ah are you referring to issue ( https://github.com/conda-forge/conda-forge-webservices/issues/132 )? Sure. Can try to take a look at some point.

Was more trying to get your thoughts on what makes sense as far as an automated welcome message for new maintainers at this point.

**Comment by isuruf** [comment]
No, conda-forge/conda-smithy#565 was done so that we could identify who was added to the team in `conda-forge-webservices`, otherwise we have no way of knowing who was added by `conda-smithy`

**Comment by jakirkham** [comment]
Ok, sorry, saw the removed member bit and started thinking this was more about removing people who signed off feedstocks.

**Comment by jakirkham** [comment]
I guess the challenge here is there are two ways we can get a new member.

1. They add a new recipe at staged-recipes.
2. They signup as a maintainer on an existing feedstock.

Given this, am thinking we should have a separate endpoint for the welcome bot that we can configure at `staged-recipes` and each feedstock. The hook could listen for [PRs being merged]( https://developer.github.com/v3/activity/events/types/#pullrequestevent ), which is easy to identify. Then we can simply comment on that PR. The other case might be if someone [pushes a commit]( https://developer.github.com/v3/activity/events/types/#pushevent ), in which case we might want to comment on the commit itself.

**Comment by isuruf** [comment]
We should drop `--add-teams` at https://github.com/conda-forge/staged-recipes/blob/master/.travis_scripts/create_feedstocks.py#L183. Then maintainers are added only at https://github.com/conda-forge/conda-forge-webservices/blob/7544e3a716b1ecbde6c5b175ca85ca8042ada9be/conda_forge_webservices/update_teams.py#L18

**Comment by jakirkham** [comment]
Hmm...what if the feedstock is renamed though? Not a hard blocker though as renaming isn't really that well supported anyways.

Side note: There might be a wrinkle in my previous suggestion. Namely we could have a race condition. It might not ever happen in practice (except maybe in feedstocks), but it is something to think about. Maybe welcoming can be part of the team updates webhook in feedstocks and only be a separate endpoint for `staged-recipes`. Might need an additional tweak to avoid commenting about welcoming users twice. 🤔

**Comment by isuruf** [comment]
> Hmm...what if the feedstock is renamed though? Not a hard blocker though as renaming isn't really that well supported anyways.

I don't understand what you are saying here.

> Might need an additional tweak to avoid commenting about welcoming users twice.

That's why I said "We should drop --add-teams at https://github.com/conda-forge/staged-recipes/blob/master/.travis_scripts/create_feedstocks.py#L183"

**Comment by jakirkham** [comment]
Let's say hypothetically tomorrow we decided to rename `pkg-a` to `pkg-b` or similar. If we didn't have add teams, the webservice wouldn't pick up on this and add a new team. Again not a hard blocker as so much of renaming is done manually. So having to do this manually as well wouldn't be too bad.

Makes sense. Figured that's what you were thinking about. Seems reasonable.

**Comment by isuruf** [comment]
Sorry. I still don't understand. I was talking about dropping `--add-teams` from staged-recipes and doing it in webservices. Renaming repo shouldn't be affected.

**Comment by jakirkham** [comment]
Ah ok. Sorry. Missed that you were referring to `staged-recipes`. Sure we can drop it there.

**Comment by jakirkham** [comment]
Would also note that we can link to whatever relevant docs show up for more details about accepting membership.

xref: https://github.com/conda-forge/conda-forge.github.io/issues/475

**Comment by jakirkham** [comment]
Addressed primarily by PR ( https://github.com/conda-forge/conda-forge-webservices/pull/195 ) and some follow-up PRs to tweak behavior.
