### ISSUE TITLE
PR/commit status

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#9]
Would be nice to have some sort of PR/commit status (green/red) to tell us if the linting is passing or not as well. This will help us avoid merging bad recipes by accident. Also, it could help contributors see in summary form what is still wrong with a recipe.

**Comment by jakirkham** [comment]
Looks like this might be very [straightforward]( https://github.com/PyGithub/PyGithub/blob/master/github/Commit.py#L154 ).

**Comment by pelson** [comment]
🎉  - great idea @jakirkham!

**Comment by jakirkham** [comment]
Thanks for implementing it.
