### ISSUE TITLE
Restart linter "button"

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#91]
Not so infrequently the linter fails to lint a recipe for some unknown reason. Currently the only way to get it to start again is try some other event in the PR to get the linter to start. Alternatively, if you have permissions, you can retrigger the webhook. It would be great if we offered some sort of "button" to retrigger the linter directly. However, we would want to make sure only the right people are able to do this (e.g. people with write permissions on the feedstock). There is also the other question of where this button lives and how it is accessed. Would love for this to be as simple as possible to avoid too much maintenance burden for this, but it may take some thought to figure out what "as simple as possible" means in this context.

**Comment by jakirkham** [comment]
Alternatively may we can just ping the linter to relint much like the re-rendering service.

**Comment by isuruf** [comment]
Should be easy to do after https://github.com/conda-forge/conda-forge-webservices/pull/102
