### ISSUE TITLE
rerendering service at request

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-webservices#97]
This would be nice to have. A reviewer can comment on a PR with `conda-forge-bot, please rerender` and then this webservice would rerender it for you.

**Comment by jakirkham** [comment]
Related to issue ( https://github.com/conda-forge/conda-forge-webservices/issues/74 ).

**Comment by jakirkham** [comment]
Could also look at triggering this by using the review request feature.

**Comment by jakirkham** [comment]
Somewhat unrelated, but it would be nice to have this with pinnings as well.

**Comment by isuruf** [comment]
PR at https://github.com/conda-forge/conda-forge-webservices/pull/102
